site_name: api
site_description: Cards Again Humanity for HacktoberFest
repo_url: https://github.com/Macaotech/backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Macaotech">Macaotech</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
